---
- hosts: localhost
  connection: local
  tasks:
    - name: Remove local files
      local_action: file path={{ item }} state=absent
      with_items:
        - ./openrc
        - ./admin-ciaorc
        - ./demo-ciaorc
        - ./clouds.yaml
        - ./certificates
        - ./images/.cnci_ready
        - ./fetch
        - /tmp/go

- hosts: controllers
  become: yes
  tasks:
    - name: Stop docker containers
      docker_container: name={{ item }} state=absent
      ignore_errors: yes
      with_items:
        - ciao-webui
        - ciao-keystone

    - name: Stop and disable services
      service: name={{ item }} state=stopped enabled=no
      with_items:
        - docker-keystone.service
        - docker-ciao-webui.service
        - ciao-controller.service
        - ciao-scheduler.service

    - name: Remove Files
      file: name={{ item }} state=absent
      with_items:
        - /etc/keystone/ssl
        - /etc/keystone/keystone.conf
        - /var/lib/mysql/
        - /etc/systemd/system/docker-keystone.service
        - /etc/systemd/system/docker-ciao-webui.service
        - /etc/systemd/system/ciao-controller.service
        - /etc/systemd/system/ciao-scheduler.service

- hosts: controllers:computes:networks
  become: yes
  tasks:
    # In ansible 2.2.0 we can drop ignore errors since it will not fail
    # when the services does not exist.
    - name: Stop services
      service: name={{ item }} enabled=no state=stopped
      with_items:
        - ciao-network.service
        - ciao-compute.service
        - docker.service
        - docker-cor.service
      ignore_errors: yes

    - name: Remove CIAO Service files
      file: name={{ item }} state=absent
      with_items:
        - /etc/systemd/system/ciao-network.service
        - /etc/systemd/system/ciao-compute.service

    - name: Remove CIAO files
      file: path={{ item }} state=absent
      with_items:
        - /etc/ciao
        - /etc/pki/ciao
        - /etc/pki/keystone
        - /var/lib/ciao
        # ClearLinux cers
        - /etc/ssl/certs/keystone_cert.pem
        # Ubuntu certs
        - /usr/local/share/ca-certificates/keystone_cert.crt
        - /etc/ssl/certs/keystone_cert.pem
        # Fedora certs
        - /etc/pki/ca-trust/source/anchors/keystone_cert.pem
        - /etc/pki/tls/certs/keystone_cert.pem

    - name: Remove CIAO files from github
      file: path={{ item }} state=absent
      with_items:
        - /usr/local/bin/ciao-controller
        - /usr/local/bin/ciao-scheduler
        - /usr/local/bin/ciao-launcher
        - /usr/local/bin/ciao-cli
        - /usr/local/bin/ciao-cert
        - /usr/local/bin/ciao-cnci-agent

    - name: Remove CIAO user
      user:
        name: ciao
        state: absent
        remove: yes
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

    - name: Remove OBS repository (Ubuntu)
      apt_repository:
        repo: deb http://download.opensuse.org/repositories/home:/clearlinux:/preview:/ciao/xUbuntu_16.04/ /
        state: absent
      when: ansible_distribution == 'Ubuntu'

    - name: Remove OBS repository (Fedora)
      yum_repository: name=ciao state=absent
      when: ansible_os_family == 'RedHat'

    - block:
        - name: Uninstall packages (Fedora)
          dnf: name={{ item }} state=absent
          with_items:
            - xorriso
            - qemu-system-x86
            - psmisc
            - docker-engine
            - ciao

        - name: Uninstall dependencies (Fedora)
          command: dnf autoremove -y
      when: ansible_os_family == "RedHat"

    - name: Uninstall packages (Ubuntu)
      apt: name={{ item }} state=absent autoremove=yes purge=yes
      with_items:
        - xorriso
        - qemu-system-x86
        - psmisc
        - docker.io
        - ciao
      when: ansible_os_family == "Debian"

    - block:
        - name: Uninstall bundles (ClearLinux)
          command: swupd bundle-remove {{ item }} {{ swupd_args | default('') }}
          with_items:
            - cloud-control
            - kvm-host
            - containers-basic
            - kernel-container
            - storage-cluster
            - storage-utils
          args:
            removes: /usr/share/clear/bundles/{{ item }}
      when: ansible_os_family == "Clear linux software for intel architecture"
